In [7]:
from sklearn import datasets

iris = datasets.load_iris()
x = iris.data
y = iris.target
print(list(y))
# import ntpath
# print(ntpath.dirname(__file__))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


##创建虚拟数据集

In [12]:
from sklearn.datasets.samples_generator import make_classification

X, y = make_classification(n_samples=6, n_features=5, n_informative=2)
for x_, y_ in zip(X, y):
    print(y_, end=': ')
    print(x_)

1: [ 0.89172557  0.77466932  0.04038974  0.26441722 -1.31745018]
0: [ 1.48512017 -1.46240143  1.13119993  1.77791758 -0.27565687]
0: [-1.69564407 -0.85409746 -2.53052124 -0.80356648  2.0737702 ]
1: [-1.39628391  1.41398531  0.79195333 -1.69054772  0.23194293]
0: [-1.14502243 -0.62905387  0.02294588 -0.51721027  1.43681625]
1: [-0.67682575  0.77472183 -0.11413772 -0.86286607  0.05017942]


##数据预处理

In [18]:
from sklearn import preprocessing
import numpy as np
# 数据归一化 基于mean和std的标准化 列的均值为0，标准差为1
X_train = np.array([[1.,-1.,2.],
                    [2.,0.,0.,],
                    [0.,1.,-1.]])
x_scaled = preprocessing.scale(X_train)
print(x_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [21]:
scaler = preprocessing.StandardScaler().fit(X_train)
print(scaler.mean_)
print(scaler.scale_)

[1.         0.         0.33333333]
[0.81649658 0.81649658 1.24721913]


In [22]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [23]:
X_test = [[-1.,1.,0.]]
scaler.transform(X_test)

array([[-2.44948974,  1.22474487, -0.26726124]])

In [24]:
X_train = np.array([[1., -1., 2.],
                    [2., 0., 0.],
                    [0., 1., -1]])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [25]:
X_test = np.array([[-3,-1,4.]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

In [27]:
data = [[0,0,3],[1,1,0],[0,2,1],[1,0,2]]
encoder = preprocessing.OneHotEncoder().fit(data)
encoder.transform(data).toarray()

array([[1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.]])

##数据集拆分

In [32]:
from sklearn.model_selection import train_test_split
X = np.array([[1,2,3],
              [1,2,3],
              [1,2,3]])
y = np.array([1,2,3])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=43)

##定义模型

In [34]:
from sklearn.linear_model import LinearRegression
#线性回归
model = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=1)

In [35]:
from sklearn.linear_model import LogisticRegression
#逻辑回归
model = LogisticRegression(penalty='l2', dual=False, tol = 0.0001, C=1.0)

In [39]:
from sklearn import naive_bayes
#高斯贝叶斯
model = naive_bayes.GaussianNB()
model = naive_bayes.MultinomialNB(alpha=1.0, fit_prior=True, 
                                  class_prior=None)
nodel = naive_bayes.BernoulliNB(alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None)

In [40]:
from sklearn import tree
# 决策树
model = tree.DecisionTreeClassifier(criterion='gini', max_depth=None, 
                                    min_samples_split=2)

In [41]:
from sklearn.svm import SVC
# 支持向量机分类
model  = SVC(C=1.0, kernel='rbf', gamma='auto')

In [42]:
from sklearn import neighbors
# k近邻
model = neighbors.KNeighborsClassifier(n_neighbors=5) # 分类
model = neighbors.KNeighborsRegressor() # 回归

In [43]:
from sklearn.neural_network import MLPClassifier
# 多层感知机
model = MLPClassifier(activation='relu', solver='adam', alpha=0.0001)

##模型评估与选择

###交叉验证

In [47]:
from sklearn.model_selection import cross_val_score
# cross_val_score(model, X, y=None, scoring=None, cv=None)