In [6]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
a = np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [5]:
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [7]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)

int32


In [9]:
dt = np.dtype('i4')
print(dt)

int32


In [10]:
dt = np.dtype('>i4')
print(dt)

>i4


In [11]:
# 结构化数据类型的使用
import numpy as np
dt = np.dtype([('age',np.int8)]) #[()
print(dt)

[('age', 'i1')]


In [12]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [13]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype=dt)
print(a['age'])

[10 20 30]


In [14]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [15]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a = np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [16]:
'''每个內建类型都有一个唯一定义它的字符代码：
'b'：布尔值
'i'：符号整数
'u'：无符号整数
'f'：浮点
'c'：复数浮点
'm'：时间间隔
'M'：日期间隔
'O'：Python对象
'S'，'a'：字节串
'U'：Unicode
'V'：原始数据
'''

"每个內建类型都有一个唯一定义它的字符代码：\n'b'：布尔值\n'i'：符号整数\n'u'：无符号整数\n'f'：浮点\n'c'：复数浮点\n'm'：时间间隔\n'M'：日期间隔\n'O'：Python对象\n'S'，'a'：字节串\n'U'：Unicode\n'V'：原始数据\n"

In [17]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [18]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
